DROP TABLE db_cli_juridica CASCADE CONSTRAINTS;

DROP TABLE mc_bairro CASCADE CONSTRAINTS;

DROP TABLE mc_cargo CASCADE CONSTRAINTS;

DROP TABLE mc_categoria_prod CASCADE CONSTRAINTS;

DROP TABLE mc_centro_distribuicao CASCADE CONSTRAINTS;

DROP TABLE mc_cidade CASCADE CONSTRAINTS;

DROP TABLE mc_cli_fisica CASCADE CONSTRAINTS;

DROP TABLE mc_cliente CASCADE CONSTRAINTS;

DROP TABLE mc_depto CASCADE CONSTRAINTS;

DROP TABLE mc_end_centro_distr CASCADE CONSTRAINTS;

DROP TABLE mc_end_cli CASCADE CONSTRAINTS;

DROP TABLE mc_end_func CASCADE CONSTRAINTS;

DROP TABLE mc_estado CASCADE CONSTRAINTS;

DROP TABLE mc_faturamento_produto CASCADE CONSTRAINTS;

DROP TABLE mc_forma_pagamento CASCADE CONSTRAINTS;

DROP TABLE mc_fornecedor CASCADE CONSTRAINTS;

DROP TABLE mc_funcionario CASCADE CONSTRAINTS;

DROP TABLE mc_item_pedido CASCADE CONSTRAINTS;

DROP TABLE mc_logradouro CASCADE CONSTRAINTS;

DROP TABLE mc_pedido CASCADE CONSTRAINTS;

DROP TABLE mc_produto CASCADE CONSTRAINTS;

DROP TABLE mc_produto_centro_distr CASCADE CONSTRAINTS;

DROP TABLE mc_produto_imagem CASCADE CONSTRAINTS;

DROP TABLE mc_promocao CASCADE CONSTRAINTS;

DROP TABLE mc_sub_categoria_prod CASCADE CONSTRAINTS;
